version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - 5678:5678
    environment:
      # As variáveis são as mesmas, mas os valores virão do Neon através do .env
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=${DB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - DB_POSTGRESDB_SCHEMA=n8n
      - DB_POSTGRESDB_SSL=true # O Neon também exige conexão segura (SSL)

      # Configs de Redis e outros permanecem iguais
      - CACHE_ENABLE=true
      - CACHE_TYPE=redis
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - CACHE_REDIS_PASSWORD=${REDIS_PASSWORD}
      - GENERIC_TIMEZONE=America/Sao_Paulo
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
  
  evolution-api:
    image: atendai/evolution-api:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      - CREATE_INSTANCE_KEY=${EVOLUTION_API_KEY}
    volumes:
      - evolution_store:/evolution/store

volumes:
  n8n_data:
  redis_data:
  evolution_store:
